application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /bower_components
  static_dir: bower_components

- url: /files
  static_dir: files

- url: /templates
  static_dir: templates

- url: /views
  static_dir: views

- url: /.*
  script: precommittee.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest